remote_theme: sujaykundu777/devlopr-jekyll  # Don't touch ( required for this theme)

# Edit your preferences below 
title: Kay van Bree
subtitle: Full Stack Web Developer
description: >- # this means to ignore newlines until "baseurl:"
  Lalallala

url: "https://kayvanbree.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# urls:
#     - text: Blog
#       url: /blog
#     - text: About Me
#       url: /about
#     - text: Contact Me
#       url : /contact
#     - text: Sample Page
#       url: /sample-page

# Edit these details 

author_logo: profile.png
author: Kay van Bree
author_bio: Bio.  
author_email: "kayvanbree@gmail.com"
author_location: The Netherlands
author_website_url: "https://kayvanbree.github.io"

author_work_experiences: 
            - company_name: Van Meijel Automatisering
#               company_logo: google.png
              company_url: https://www.vanmeijel.nl/en/
              designation: Software Engineer
              description: We are working on building a new Angular frontend for an old Delphi application.
              visibility: true
            - company_name: Yacht
              company_url: https://www.yacht.nl/
              designation: Software Engineer
              description: Participant to the first MostDev talent program, a course by Capgemini.
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: false

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false

# social links
# twitter_username: johndoe
github_username:  kayvanbree
# facebook_username: johndoe
linkedin_username: kayvanbree
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments using disqus
# disqus_shortname: sujay-kundu  

# wakatime username
# wakatime_username: sujaykundu777

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
# google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


